services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - next-nest-products
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"

    environment:
      HOST: host.docker.internal
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASS: root
      DB_NAME: crud

      JWT_SECRET: superSecretKeyForProd
      PORT: 4000

    depends_on:
      - db
    networks:
        - next-nest-products


volumes:
  postgres_data:

networks:
  next-nest-products:
    driver: bridge